"use strict";
exports.__esModule = true;
exports.suiteParams = [
    "smoke",
    "admv2",
    "calculation",
    "impersonalization",
    "journal",
    "printedForms",
    "sale",
    "userProfile",
    "osago",
    "kasko",
    "snugHome",
    "express",
    "myChoice",
    "constructorHome",
    "assuranceApartment",
    "assuranceHome",
    "boxVHIAntimite",
    "boxVHIMigrant",
    "personalAccident",
    "boxAccident",
    "travelingAbroad",
    "crossKasko",
    "crossOsago",
    "crossBoxAccident",
    "crossAssuranceHome",
    "crossAssuranceApartment",
    "crossConstructorHome",
    "crossMyChoice",
    "crossExpress",
    "crossSnugHome",
    "crossPersonalAccident",
    "crossTravelingAbroad"
];
//# sourceMappingURL=suite.js.map